require("core.options")
require("core.mappings")
require("core.autocmds")
require("core.highlights")
require("core.filetype")
require("core.abbrev")
require("core.plugins")
require("vim._core.ui2").enable()
