#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2020 Saurabh Charde <saurabhchardereal@gmail.com>
#

# This will output a file (missing_blobs.txt) containing a list of missing blobs
# required by their dependencies
# (source: https://github.com/joshuous/AospMissingBlobs)

SCRIPT_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
JAR_PATH="${SCRIPT_PATH}"/../bin/MissingBlobs.jar

if [ -z "$ANDROID_PRODUCT_OUT" ]; then
    echo "Run after lunching your device!"
    exit 1
fi

# Add paths to check for blobs
BLOBS_PATH=(
    system/lib
    system/lib64
    system/lib/vndk-29
    system/lib/vndk-sp-29
    system/lib64/vndk-29
    system/lib64/vndk-sp-29
    system/product/lib
    system/product/lib64
    system/system_ext/lib
    system/system_ext/lib64
    vendor/lib
    vendor/lib64
    vendor/bin/hw
    system/bin/hw
    system/apex/*/lib
    system/apex/*/lib64
    vendor/apex/*/lib
    vendor/apex/*/lib64
)

[[ ! -f "${JAR_PATH}" ]] && {
    curl --create-dirs -LOs tmp https://github.com/saurabhchardereal/scripts/raw/master/bin/MissingBlobs.jar
    JAR_PATH=${ANDROID_PRODUCT_OUT}/tmp/MissingBlobs.jar
    trap 'rm -rf ${ANDROID_PRODUCT_OUT}/tmp;' EXIT
}

java -jar "${JAR_PATH}" ${BLOBS_PATH[@]/#/$ANDROID_PRODUCT_OUT/} >"${PWD}"/missing_blobs.txt
