#!/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2020 Saurabh Charde <saurabhchardereal@gmail.com>
#

# This will output a file (missing_blobs.txt) containing a list of missing blobs
# required by their dependencies
# (source: https://github.com/joshuous/AospMissingBlobs)

SCRIPT_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

if [ -z "$ANDROID_PRODUCT_OUT" ]; then
    echo "Run after lunching your device!"
    return 1
fi

cd "$ANDROID_PRODUCT_OUT"

# Add paths to check for blobs
BLOBS_PATH="
    system/lib \
    system/lib64 \
    system/lib/vndk-29 \
    system/lib/vndk-sp-29 \
    system/lib64/vndk-29 \
    system/lib64/vndk-sp-29 \
    system/product/lib \
    system/product/lib64 \
    vendor/lib \
    vendor/lib64 \
    vendor/bin/hw \
    system/bin/hw \
    system/apex/*/* \
    vendor/apex/*/* "

java -jar "$SCRIPT_PATH"/../bin/MissingBlobs.jar \
    $BLOBS_PATH >missing_blobs.txt
