#!/bin/bash

rule() { bspc rule -a "$@"; }
config() { bspc config "$@"; }

# Start picom
picom --experimental-backends --config "$HOME"/.config/picom/picom.conf &

# Set wallpaper
feh --bg-fill "$HOME"/Downloads/bg.jpg

# Start sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

# BSPWM desktop layout
bspc monitor -d 1 2 3 4 5

# BSPWM config
config border_width 1
config window_gap 10
config split_ratio 0.52
config borderless_monocle true
config gapless_monocle true
config focused_border_color "$(xrdb -query | awk '/color5:/ {print $2}')"
config presel_feedback_color "$(xrdb -query | awk '/color15:/ {print $2}')"
# config focus_follows_pointer true
config pointer_modifier mod4         # super
config pointer_action1 move          # super + left click
config pointer_action2 resize_side   # super + middle click
config pointer_action3 resize_corner # super + right click

# BSPWM rules
# bspc rule -a org.wezfurlong.wezterm state=floating
rule firefox desktop=2 follow=on
rule firefox:Places state=floating # FF downloads/history windows
rule TelegramDesktop desktop=3 follow=on
rule obs desktop=5 follow=off

# Launch Polybar
~/.config/polybar/launch.sh

# Set proper cursor
xsetroot -cursor_name left_ptr &
