# Continue downloading a partially downloaded file if a corresponding control file exists
continue

# downloads dir
dir=${HOME}/Downloads

# File allocation (best for ext4 and newer file systems)
file-allocation=falloc

# Download a list of line, or TAB separated URIs found in this file
# input-file=${HOME}/.aria2/input.conf

log-level=warn

# Set a maximum of 4 connections to each server per file
max-connection-per-server=4

# Only split the file if the size is larger than 2*5MB = 10MB
min-split-size=5M

# Run the exit command and exit the shell once the download session is complete
on-download-complete=exit
