" SPDX-License-Identifier: GPL-3.0-or-later
"
" Copyright (C) 2020 Saurabh Charde <saurabhchardereal@gmail.com>
"

"==============================================================================
" GENERAL SETTINGS
"==============================================================================

filetype plugin indent on   " Used for indentation based on file-type
syntax enable               " Enable syntax highlighting
set nowrap                  " Do not wrap code by default
set expandtab               " Expand TABs to spaces
set shiftwidth=4            " Indents will have a width of 4
set tabstop=4               " The width of a TAB is set to 4.
                            " Still it is a \t. It is just that
                            " Vim will interpret it to be having
                            " a width of 4.
set softtabstop=4           " Sets the number of columns for a TAB
set shell=bash              " Set default shell to bash coz zsh isn't POSIX-compatible
set incsearch               " Incrementally highlights search patterns 

" Highlight trailing whitespace in red
hi ExtraWhitespace ctermbg=darkred
match ExtraWhitespace /\s\+$/
au BufWinEnter * match ExtraWhitespace /\s\+$/

" Highlight tabs in yellow
hi Tabs ctermbg=yellow
call matchadd('Tabs', '\t')
au BufWinEnter * call matchadd('Tabs', '\t')
if version >= 702
  au BufWinLeave * call clearmatches()
endif

" Source plugins.vim to load vim plugins
so ~/.vim/plugins.vim

" Write {swap,viminfo,backup} to ~/.vim/{swap,viminfo,backup}
" https://vi.stackexchange.com/a/20067
if !isdirectory('~/.vim/swap')
    silent call system('mkdir -p ~/.vim/{swap,backup}')
    set backupdir=~/.vim/backup//
    set directory=~/.vim/swap//
endif
set viminfo+=n~/.vim/viminfo
