#!/data/data/com.termux/files/usr/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2020 Saurabh Charde <saurabhchardereal@gmail.com>
#

SCRIPT_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source "$SCRIPT_PATH"/../common
source "$SCRIPT_PATH"/git

# Packages to install
prInfo "Installing packages ..."
pkg install --no-install-recommends -y \
    antibody \
    nano \
    vim \
    openssh \
    gnupg \
    binutils \
    wget \
    zsh

# Theme
setupTheme() {
    # use Dracula color scheme & Hack font by default
    prInfo "Setting up theme ..."
    curl -Lso "$HOME"/.termux/colors.properties https://raw.githubusercontent.com/adi1090x/termux-style/master/colors/dracula.properties
    curl -Lso "$HOME"/.termux/font.ttf https://github.com/adi1090x/termux-style/raw/master/fonts/Hack.ttf
}

# Settings I use for moi setup
[[ ! -d ~/.termux ]] && mkdir ~/.termux
echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" >~/.termux/termux.properties
setupTheme
git_setup

# Setup dotfiles
echo "export ZDOTDIR=~/.zsh" >"${HOME}"/.zshenv
ln -sf "$SCRIPT_DIR"/dotfiles/.zsh "${HOME}"
ln -sf "$SCRIPT_DIR"/dotfiles/.vim "${HOME}"

# Switch to zsh
chsh -s zsh

prSucc "Setup done!"
