#!/data/data/com.termux/files/usr/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2020 Saurabh Charde <saurabhchardereal@gmail.com>
#

SCRIPT_PATH=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
SCRIPT_DIR=$(dirname "${SCRIPT_PATH}")

source "$SCRIPT_PATH"/git

# Packages to install
pkg install --no-install-recommends -y \
    antibody \
    nano \
    vim \
    openssh \
    gnupg \
    binutils \
    wget \
    zsh

# Theme
setupTheme() {
    # use Dracula color scheme & Hack font by default
    # can be changed after installing termux-style anyway
    TERMUX_STYLE="$SCRIPT_DIR"/modules/termux-style
    cp "$TERMUX_STYLE"/colors/dracula.properties "$HOME"/.termux/colors.properties
    cp "$TERMUX_STYLE"/fonts/Hack.ttf "$HOME"/.termux/font.ttf
}

# Settings I use for moi setup
mkdir ~/.termux && touch ~/.termux/termux.properties
echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" >~/.termux/termux.properties
[[ -d "$TERMUX_STYLE" ]] && setupTheme
git_setup

# Setup dotfiles
echo "export ZDOTDIR=~/.zsh" >"${HOME}"/.zshenv
ln -sf "$SCRIPT_DIR"/dotfiles/.zsh "${HOME}"
ln -sf "$SCRIPT_DIR"/dotfiles/.vim "${HOME}"

# Switch to zsh
chsh -s zsh

echo "Setup done!"
